config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'posts#index'
  resources :posts
  resources :photos

  get '/рубрика/:title', to: 'posts#index', as: 'catigories'
  get '/статья/:title', to: 'posts#seo_show', as: 'seo_post', :constraints => {:title => /.+/}

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post
	has_one :main_to_post, :class_name => 'Post', :foreign_key => :main_photo_id, :dependent => :nullify
	mount_uploader :image, PhotoUploader

end

app/models/post.rb
class Post < ApplicationRecord
  has_many   :photos,  :dependent => :destroy
  belongs_to  :main_photo, :class_name => 'Photo',   required: false
  has_and_belongs_to_many :tags


  def main_image
    if  main_photo && main_photo.image
      main_photo.image_url
    else
      nil
    end
  end

  def prev(limit=1)
     item = Post.where(state: 1).where('id < ?', id ).last(limit)
     item = Post.where(state: 1).first(limit) if item == []
     limit == 1 ? item[0] : item
  end

  def next(limit=1)
    item = Post.where(state: 1).where('id > ?', id ).first(limit)
    item = Post.where(state: 1).first(limit) if item == []
    limit == 1 ? item[0] : item
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
    has_and_belongs_to_many :posts
    scope :active,  -> { where(active: true) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :left_post
  before_action :authenticate_user!, except: [:index, :show, :seo_show]
  

  def left_post
   @left_post = Post.where(state: 1).last(3)
   @left_post.where.not(id: @post.id) if @post
   @tags = Tag.active 
  end

  def is_admin?
    redirect_to root_path unless current_user.try(:admin?)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, except: [:index, :create, :new, :seo_show]
  before_action :init_page
  before_action :is_admin?, only: [:edit, :update, :destroy, :new]

  def index
    state = [1]
    state << 0 if current_user.try(:admin?)
    @seo_title = 'Блог  Сигачева Александра. Страница ' + @page.to_s
    @posts = []
    if params[:title]
      tag = Tag.find_by(title: params[:title])
      @posts = tag.posts.order('id desc').paginate(page: @page)
    else
      @posts = Post.where(state: state).order('id desc').paginate(page: @page)
    end
    ids = @posts.map(&:id)
    @seo_desc =  @posts.map(&:title).join(' ')
    @seo_keywords = @seo_desc.split(/\s+/).uniq.select{|w| w.size > 5 }.join(', ')
    @left_post = Post.where(state: 1).where.not(id: ids).last(3)
  end

  def show
    @seo_title = @post.seo_title
    @seo_desc = @post.seo_desc
    @seo_keywords = @post.seo_keyword
  end

  def seo_show
    left_post
    @post = Post.find_by(title: params[:title])
    @seo_title = @post.seo_title
    @seo_desc = @post.seo_desc
    @seo_keywords = @post.seo_keyword
    render 'posts/show'
  end

  def edit

  end

  def update
    if 	@post.update_attributes(post_permit)
      photos = add_photos(@post)

      if !@post.main_photo_id && photos
        @post.update_attributes(main_photo_id: photos.sample.id)
      end  

      @post.tags.destroy_all
      Tag.where(id: params[:tag_ids]).each do |tag|
         @post.tags << tag
      end
      @post.save
      redirect_to edit_post_path(@post)
    else
      render :edit
    end

  end

  def new
    @post = Post.new
  end

  def create
    if  @post =	Post.create(post_permit)
      photos = add_photos(@post)
      if !@post.main_photo_id && photos
        @post.update_attributes(main_photo_id: photos.sample.id)
      end  

      Tag.where(id: params[:tag_ids]).each do |tag|
        @post.tags << tag
      end
    end
  end

  private

  def add_photos(post)
     return  false  if params[:post][:photos].blank?
     params[:post][:photos].map do |i|
       photo =  Photo.new(post_id: post.id)
       photo.image = i['image']
       photo.save
       photo
     end
  end


  def init_page
    @page = [1, params[:page].to_i ].max
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def post_permit
    params[:post].permit(:title, :seo_title, :seo_desc, :seo_keyword, :short, :state, :content, :pos )
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

    def index
        
    end

    def create

    end

    def update

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="ru-RU">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="profile" href="http://gmpg.org/xfn/11">
<title><%= @seo_title || @title %> Сигачев - РФ</title>
<%= stylesheet_link_tag :application %>
<%= javascript_include_tag :application %>
<%= csrf_meta_tag %>
<meta name="Description" content="<%= @seo_desc  %>">
<meta name="Keywords" content="<%= @seo_keywords  %>">

<link rel='stylesheet' id='olsen-light-google-font-css'  href='https://fonts.googleapis.com/css?family=Lora%3A400%2C700%2C400italic%2C700italic%7CLato%3A400%2C400italic%2C700%2C700italic&#038;ver=4.8.1' type='text/css' media='all' />
<style type="text/css" id="wp-custom-css">
.tagline,.site-bar,.entry-meta,.entry-title,.entry-tags,#paging,.btn,.comment-reply-link,input[type="button"],input[type="submit"],input[type="reset"],button,.read-more{text-transform:uppercase}</style>
</head>
<body class="post-template-default single single-post postid-251 single-format-video" itemscope="itemscope" itemtype="http://schema.org/WebPage">
<div id="page">
<div class="container">
<div class="row">
<div class="col-md-12">
<header id="masthead" class="site-header group" role="banner" itemscope="itemscope" itemtype="http://schema.org/Organization">
<div class="site-logo">
<h1 itemprop="name">
 <a itemprop="url" href="/">
 <div itemprop="logo">Сигачев.РФ</div>
 </a>
</h1>
<p class="tagline">
Персональный блог</p>
</div>
<div class="site-bar group">
 <nav class="nav" role="navigation" itemscope="itemscope" itemtype="http://schema.org/SiteNavigationElement">
<ul id="menu-main" class="navigation">
<li id="menu-item-435" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-435">
<a href="/">
Главная</a>
</li>
</ul>
 <a class="mobile-nav-trigger" href="#mobilemenu">
<i class="fa fa-navicon">
</i>
 Menu</a>
 </nav>
<div id="mobilemenu">
</div>
<div class="site-tools">
<ul class="socials">
  <li>
  <a href="https://vk.com/asigachev" target="_blank">
  <i class="fa fa-vk">
  </i>
  </a>
  </li>
<li>
<a href="https://www.facebook.com/alexander.sigatchov" target="_blank">
<i class="fa fa-facebook">
</i>
</a>
</li>
<li>
<a href="https://twitter.com/asigatchov" target="_blank">
<i class="fa fa-twitter">
</i>
</a>
</li>
</ul>
</div>
</div>
</header>
<div id="site-content">
<div class="row">
<div class="col-md-8">
 <main id="content" role="main" itemprop="mainContentOfPage" itemscope="itemscope" itemtype="http://schema.org/Blog">
<div class="row">
<div class="col-md-12">
<%= yield %>
 </main>
</div>
<div class="col-md-4">
<div class="sidebar sidebar-right" role="complementary" itemtype="http://schema.org/WPSideBar" itemscope="itemscope">
 <aside id="ci-about-2" class=" widget group widget_ci-about">
<h3 class="widget-title">
О Себе</h3>
<div class="widget_about group">
<p class="widget_about_avatar">
<img src="https://pp.userapi.com/c840739/v840739791/1962/5SqWxUy5v58.jpg" class="img-round" alt="" />
</p>

<p>
<b>Навыки:</b> Проектирование, разработка и сопровождение высоконагруженных систем.<br>
<b>Технологии:</b>
Ruby on Rails,  Docker, elasticsearch,  EFK, Clickhouse, Javascript
Mysql, Redis
</p>
</div>
</aside>
<aside id="ci-socials-2" class="widget group widget_ci-socials">
<h3 class="widget-title">
Социальные сети</h3>
<ul class="socials">
  <li>
  <a href="https://vk.com/asigachev" target="_blank">
  <i class="fa fa-vk">
  </i>
  </a>
  </li>
<li>
<a href="https://www.facebook.com/alexander.sigatchov" target="_blank">
<i class="fa fa-facebook">
</i>
</a>
</li>
<li>
<a href="https://twitter.com/asigatchov" target="_blank">
<i class="fa fa-twitter">
</i>
</a>
</li>
</ul>
 </aside>
<aside id="ci-latest-posts-2" class="widget group widget_ci-latest-posts">
<h3 class="widget-title">
Другие статьи</h3>
<ul class="widget_posts_list widget_posts_list_alt">
<% @left_post.each do |post|   %>
<li>
 <article class="entry post-<%= post.id %> post type-post status-publish format-image has-post-thumbnail hentry category-looks tag-autumn tag-dress tag-photography post_format-post-format-image">
<div class="entry-meta">
 <time class="entry-date" datetime="<%= post.created_at %>">
<%= post.created_at.strftime("%Y-%m-%d") %></time>
</div>
<div class="entry-featured">
 <a href="<%= post_path(post) %>">
 <img width="665" height="435" src="<%= post.main_image %>" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" />
 </a>
</div>
<h2 class="entry-title">
<a href="<%= post_path(post) %>">
<%= post.title%></a>
</h2>
 </article>
</li>
<% end %>
</ul>
 </aside>
<aside id="search-2" class="widget group widget_search">
<form action="/search" class="searchform" method="get" role="search">
<div>
 <label class="screen-reader-text">
Search for:</label>
 <input type="text" placeholder="Search" name="s" value="">
 <button class="searchsubmit" type="submit">
<i class="fa fa-search">
</i>
<span class="screen-reader-text">
Поиск</span>
</button>
</div>
</form>
</aside>
<aside id="categories-2" class="widget group widget_categories">
<h3 class="widget-title">
Рубрики</h3>
<ul>
<%  @tags.each do |tag| %>
<li class="cat-item cat-item-2">
    <%= link_to(tag.title, catigories_path({title: tag.title})) %>
    <span class="ci-count">(<%= tag.posts.count %>)  </span>
</li>
<% end %>
</ul>
 </aside>
</div>
</div>
</div>
</div>
<footer id="footer">
<div class="row">
<div class="col-md-12">
<div class="footer-widget-area" data-auto="1" data-speed="300">
 <aside id="null-instagram-feed-2" class="widget group null-instagram-feed">

<p class="clear">
<a href="//instagram.com/marieclairemag/" rel="me" target="_self">
Follow Us</a>
</p>
</aside>
</div>
</div>
</div>
<div class="site-bar group">
 <nav class="nav">
<ul id="menu-footer" class="navigation">
<li id="menu-item-460" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-460">
<a href="/">
IT</a>
</li>
<li id="menu-item-461" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-461">
<a href="/">
Хобби</a>
</li>
</ul>
 </nav>
<div class="site-tools">
<ul class="socials">
  <li>
  <a href="https://vk.com/asigachev" target="_blank">
  <i class="fa fa-vk">
  </i>
  </a>
  </li>
  <li>
  <a href="https://www.facebook.com/alexander.sigatchov" target="_blank">
  <i class="fa fa-facebook">
  </i>
  </a>
  </li>
  <li>
  <a href="https://twitter.com/asigatchov" target="_blank">
  <i class="fa fa-twitter">
  </i>
  </a>
  </li>
  </</ul>
</div>
</div>
<div class="site-logo">
<h3>
 <a href="/">
 Сигачев.РФ
 </a>
</h3>
<p class="tagline">
 <a href="/" title="Персональный блог Александра Сигачева">
Персональный блог</a>
 by <a href="/">
asigatchov</a>
</p>
</div>
 </footer>
</div>
</div>
</div>
</div>
<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter24546758 = new Ya.Metrika({
                    id:24546758,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true,
                    webvisor:true,
                    trackHash:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/24546758" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
 </body>
</html>

app/views/photos/_photo_thumb.html.erb
<div class="photo_thumb" id="photo_thumb_<%= photo.id  %>">
<% if photo && photo.image_url  %>
<%=  image_tag(photo.image_url(:thumb), :title=>photo.id )%>
<% end %>
<div class="action"><%= link_to 'Удалить', photo_path(photo), :method => :delete, :remote => true %></div>
</div>

app/views/photos/destroy.js.erb
$('#photo_thumb_<%= params[:id] %>').remove()
$('#photo_<%= params[:id] %>').remove()

app/views/posts/_comments.html.erb
<div id="comments">
<section id="respond">
<div id="form-wrapper" class="group">
<div id="respond" class="comment-respond">
<h3 id="reply-title" class="comment-reply-title">
Leave a Reply <small>
<a rel="nofollow" id="cancel-comment-reply-link" href="/preview/olsenlight/2016/09/11/my-trip-to-barcelona/#respond" style="display:none;">
Cancel reply</a>
</small>
</h3>
<form action="https://www.cssigniter.com/preview/olsenlight/wp-comments-post.php" method="post" id="commentform" class="comment-form" novalidate>
<p class="comment-notes">
<span id="email-notes">
Your email address will not be published.</span>
 Required fields are marked <span class="required">
*</span>
</p>
<p class="comment-form-comment">
<label for="comment">
Comment</label>
<textarea id="comment" name="comment" cols="45" rows="8" maxlength="65525" aria-required="true" required="required">
</textarea>
</p>
<p class="comment-form-author">
<label for="author">
Name <span class="required">
*</span>
</label>
 <input id="author" name="author" type="text" value="" size="30" maxlength="245" aria-required='true' required='required' />
</p>
<p class="comment-form-email">
<label for="email">
Email <span class="required">
*</span>
</label>
 <input id="email" name="email" type="email" value="" size="30" maxlength="100" aria-describedby="email-notes" aria-required='true' required='required' />
</p>
<p class="comment-form-url">
<label for="url">
Website</label>
 <input id="url" name="url" type="url" value="" size="30" maxlength="200" />
</p>
<p class="form-submit">
<input name="submit" type="submit" id="submit" class="submit" value="Post Comment" />
 <input type='hidden' name='comment_post_ID' value='251' id='comment_post_ID' />
 <input type='hidden' name='comment_parent' id='comment_parent' value='0' />
</p>
<p style="display: none;">
<input type="hidden" id="akismet_comment_nonce" name="akismet_comment_nonce" value="5a4d15e425" />
</p>
<p style="display: none;">
<input type="hidden" id="ak_js" name="ak_js" value="235"/>
</p>
</form>
</div>
</div>
 </section>
</div>

app/views/posts/_form.erb
<div class="form">
<%= form_for(@post, :url => (@post.new_record? ? posts_path : post_path(@post)), :html =>{ :multipart => true}  ) do |f|  %>
<div class="field">
<%= f.label :title, 'Заголовок' %>
<%= f.text_field :title  %>
</div>
<div class="field">
<%= label_tag 'image', 'Картинка' %>
<%= file_field_tag 'post[photos][][image]' %>
<%= file_field_tag 'post[photos][][image]' %>
<%= file_field_tag 'post[photos][][image]' %>
<%= file_field_tag 'post[photos][][image]' %>
</div>
<div class="field">
<%= f.label :seo_title, 'SEO Заголовок' %>
<%= f.text_field :seo_title  %>
</div>
<div class="field">
<%= f.label :seo_desc, 'SEO Desc' %>
<%= f.text_area :seo_desc, :class => 'small'  %>
</div>
<div class="field">
<%= f.label :seo_keyword, 'SEO Keyword' %>
<%= f.text_area :seo_keyword, :class => 'small'  %>
</div>
<div class="field">
<%= f.label :short, 'Анотация' %>
<%= f.text_area :short, :class => 'small'  %>
</div>
<div class="field">
<%= f.label :content, 'Контент' %>
<%= f.text_area :content  %>
</div>

<div class="field">
<%= f.label :state, 'Опубликовать', :style => 'display:inline' %>
<%= f.check_box :state  %>
</div>
<div class="field">
<%= f.label 'export_vk', 'Экспорт в VK.COM', :style => 'display:inline' %>
<%= check_box_tag :export_vk, 1   %>
</div>

<div class="field" id="tags_list">
<% Tag.where(active: true).each do |tag| %>
<div style="display:inline;">
  <%= f.label "tag[#{tag.id}]", tag.title, :style => '' %>
  <%= check_box_tag "tag_ids[]", tag.id, @post.tags.include?(tag)  %>
</div>
<% end %>
</div>

<div class="field">
<%= f.label :pos, 'Позиция для сортировки' %>
<%= f.text_field :pos  %><br>
<%= f.submit 'Сохраиить' %>
</div>
</div>
<% end %>

app/views/posts/edit.html.erb
<h2>
Редактировать
</h2>

<%= render 'form' %>

<% @post.photos.each do |photo| %>
<%= render :partial => 'photos/photo_thumb', :locals => {:photo =>photo  } %>
<% end  %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<article id="entry-<%=post.id %>" class="entry post-<%=post.id %> post type-post status-publish format-gallery has-post-thumbnail hentry category-fashion tag-autumn tag-dress tag-photography post_format-post-format-gallery" itemscope="itemscope" itemtype="http://schema.org/BlogPosting" itemprop="blogPost">
<div class="entry-meta entry-meta-top">
<p class="entry-categories">
<a href="/" rel="category tag">
IT</a>
</p>
</div>
<h2 class="entry-title" itemprop="headline">
<a href="<%= post_path(post) %>">
<%= post.title %></a>
</h2>
<div class="entry-meta entry-meta-bottom">
<time class="entry-date" itemprop="datePublished" datetime="<%= post.created_at %>">
  <%= post.created_at.strftime("%Y-%m-%d") %>
</time>
<% if false %>
<a href="https://www.cssigniter.com/preview/olsenlight/2016/09/16/next-level-mustache/#respond" class="entry-comments-no">
No Comments</a>
<% end %>>
</div>
<div class="entry-featured">
<a href="<%= post_path(post) %>">
<img width="665" height="435" src="<%= post.main_image %>" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" itemprop="image" />
</a>
</div>
<div class="entry-content" itemprop="text">
  <%= post.short %>
</div>
<div class="entry-utils group">
<a href="<%= post_path(post) %>" class="read-more">
Читать далее</a>
<% if current_user.try(:admin?)%>
<a href="<%= edit_post_path(post) %>" class="read-more">
Редактировать</a>
<% end %>
<ul class="socials">
<li>
<a href="https://www.facebook.com/sharer.php?u=<%= post_url(post) %>" target="_blank" class="social-icon">
<i class="fa fa-facebook">
</i>Персональный
</a>
</li>
<li>
<a href="https://twitter.com/share?url=<%= post_url(post) %>" target="_blank" class="social-icon">
<i class="fa fa-twitter">
</i>
</a>
</li>
<li>
<a href="https://plus.google.com/share?url=<%= post_url(post) %>" target="_blank" class="social-icon">
<i class="fa fa-google-plus">
</i>
</a>
</li>
</ul>
</div>
</article>
<% end %>

app/views/posts/new.html.erb
<h2>Новая запись</h2>
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="row">
<div class="col-md-12">
<article id="entry-<%= @post.id %>" class="entry post-<%= @post.id %> post type-post status-publish format-video has-post-thumbnail hentry category-travel tag-autumn tag-dress tag-photography post_format-post-format-video" itemscope="itemscope" itemtype="http://schema.org/BlogPosting" itemprop="blogPost">
<div class="entry-meta entry-meta-top">
<p class="entry-categories">
 <a href="/" rel="category tag">
IT</a>
</p>
</div>
<h1 class="entry-title" itemprop="headline">
 <%= @post.title  %></h1>

<% if current_user.try(:admin?)%>
<div class="entry-utils group">
<a href="<%= edit_post_path(@post) %>" class="read-more">
Редактировать</a>
</div>
<% end %>

<div class="entry-meta entry-meta-bottom">
  <time class="entry-date" itemprop="datePublished" datetime="<%= @post.created_at %>">
    <%= @post.created_at.strftime("%Y-%m-%d") %>
  </time>
</div>
<div class="entry-featured">
 <a class="ci-lightbox" href="<%= @post.main_image %>">
 <img width="665" height="435" src="<%= @post.main_image %>" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" itemprop="image" />
 </a>
</div>
<div class="entry-content" itemprop="text">
  <%=  @post.content.html_safe %>
</div>
<div class="entry-utils group">
<ul class="socials">
<li>
<a href="https://www.facebook.com/sharer.php?u=<%= post_url(@post) %>" target="_blank" class="social-icon">
<i class="fa fa-facebook">
</i>
</a>
</li>
<li>
<a href="https://twitter.com/share?url=<%= post_url(@post) %>" target="_blank" class="social-icon">
<i class="fa fa-twitter">
</i>
</a>
</li>
<li>
<a href="https://plus.google.com/share?url=<%= post_url(@post) %>" target="_blank" class="social-icon">
<i class="fa fa-google-plus">
</i>
</a>
</li>
</ul>
</div>
<div id="paging" class="group">
 <a href="<%= post_path(@post.prev) %>" class="paging-standard paging-older">
Previous Post</a>
 <a href="<%= post_path(@post.next) %>" class="paging-standard paging-newer">
Next Post</a>
</div>


<div class="entry-related">
<h6>
Вам может понравиться</h6>
<div class="row">

<% @post.prev(3).each do |post_prev|  %>
  <div class="col-sm-4">
     <article class="entry post-<%= post_prev.id %> post type-post status-publish format-image has-post-thumbnail hentry category-looks tag-autumn tag-dress tag-photography post_format-post-format-image">
       <div class="entry-meta">
          <time class="entry-date" datetime="<%= post_prev.created_at %>"><%= post_prev.created_at.strftime("%Y-%m-%d") %></time>
       </div>
       <div class="entry-featured">
       <a href="<%= post_path(post_prev) %>">
           <img width="665" height="435" src="<%=  post_prev.main_image %>" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" />
        </a>
     </div>
     <h2 class="entry-title">
     <a href="<%= post_path(post_prev) %>"><%= post_prev.title %></a>
    </h2>
  </article>
 </div>
<% end %>

 </div>
 </div>



 </article>
 </div>
 </div>